# Ultimate Jekyll Properties
uj:
  cache_breaker: null
  # environment: "production" # DEPRECATED: use jekyll.environment instead

# Theme
theme:
  html:
    class: ""
  body:
    class: ""
  nav:
    enabled: true
  main:
    class: ""
  footer:
    enabled: true

# Comments
comments:
  gisqus:
    repo: "Distalk/giscus" # string, example: somiibo/giscus
    repo-id: "R_kgDOJ-chGA" # string, example: R_kgDOJ-chGA
    category: "Giscus" # string, example: Giscus
    category-id: "DIC_kwDOJ-chGM4CYD4O" # string, example: DIC_kwDOJ-chGM4CYD4O

# Advertising
advertising:
  google-adsense:
    client: "ca-pub-7372939085773564" # false to disable, example: ca-pub-7372939085773564
    display-slot: "9023354299" # example: 9023354299
    in-article-slot: "7329067043" # example: 7329067043
    in-feed-slot: "5986127415" # example: 5986127415
    multiplex-slot: "8772072856" # example: 8772072856
  cse:
    site-id: "5ad46a4c7412db0ae" # example: 5ad46a4c7412db0ae

# Escape shortcuts
characters:
  asterisk: "*"
  brace-left: "{"
  brace-right: "}"
  brace-both: "{}"
  bracket-left: "["
  bracket-right: "]"
  bracket-both: "[]"
  copyright: "Â©"
  underscore: "_"

# Build settings
markdown: kramdown
strict_front_matter: true
plugins:
  - jekyll-paginate-v2
  # - jekyll-liquify
  - jekyll-uj-powertools
  # - jekyll-truthyfalsy

# Parallel
parallel_build:
  enabled: true          # Enable/disable parallel builds (default: true)
  threads: 8             # Number of threads (default: number of CPU cores)
  min_items: 1          # Minimum items before parallelizing (default: 10)

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
  - .placeholder

# Include in processing
include:
  - .well-known
  - __
